services:
  host: localhost
  port: 8081

config:
  csrf:
    age: 600 #seconds
    domain: "localhost"
    path: "/"
  session:
    age: 600 #seconds
    domain: "localhost"
    path: "/"

database:
  read:
    driver: postgresql
    host: localhost
    port: 5433
    database: sso
    schema: sso
    username: ryuze
    password: asd123qwe
  write:
    driver: postgresql
    host: localhost
    port: 5433
    database: sso
    schema: sso
    username: ryuze
    password: asd123qwe