services:
  host: "0.0.0.0"
  port: 8080

config:
  session:
    secret: fa7168ff4543c7458c26748786ed596d2730a6a8
    domain: localhost
  url:
    internal:
      domain: "http://localhost:8080"
      path:
        authorize: "/api/v1/authorize"
    redirect_fe:
      login: "http://localhost:3000/"
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
  debug: false

secret:
  internal:
    private: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIC1wfYU7WzOZ4AnNph9xA0Z42XvdNJNCQ02GPNSVhc7eoAoGCCqGSM49\nAwEHoUQDQgAEvXsnS6kT7zD5ebOS57gFv4+NHZx5q47xQgmZZUn5ZEd/Me8CPuVv\n+nCW2VY3cM1z3dcZ6c9LGokCRoIZ5s190g==\n-----END EC PRIVATE KEY-----"
    public: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvXsnS6kT7zD5ebOS57gFv4+NHZx5\nq47xQgmZZUn5ZEd/Me8CPuVv+nCW2VY3cM1z3dcZ6c9LGokCRoIZ5s190g==\n-----END PUBLIC KEY-----"

database:
  read:
    driver: postgresql
    host: 192.168.0.250
    port: 5432
    database: postgres
    schema: sso
    username: postgres
    password: asd123qwe
  write:
    driver: postgresql
    host: 192.168.0.250
    port: 5432
    database: postgres
    schema: sso
    username: postgres
    password: asd123qwe