services:
  host: "0.0.0.0"
  port: 8080

config:
  session:
    secret: fa7168ff4543c7458c26748786ed596d2730a6a8
    domain: ".idtecsi.my.id"
  url:
    internal:
      domain: "https://sso.idtecsi.my.id"
      path:
        authorize: "/api/v1/authorize"
    redirect_fe:
      login: "https://login.idtecsi.my.id/login"
  cors:
    allow_origins:
      - "https://login.idtecsi.my.id"
      - "https://inventory.idtecsi.my.id"
      - "http://localhost:2000"
      - "http://localhost:5713"
      - "http://localhost:5714"
  debug: false

secret:
  internal:
    callback_url: "https://sso.idtecsi.my.id/v1/api/callback"
    key: ES256
    private: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIC1wfYU7WzOZ4AnNph9xA0Z42XvdNJNCQ02GPNSVhc7eoAoGCCqGSM49\nAwEHoUQDQgAEvXsnS6kT7zD5ebOS57gFv4+NHZx5q47xQgmZZUn5ZEd/Me8CPuVv\n+nCW2VY3cM1z3dcZ6c9LGokCRoIZ5s190g==\n-----END EC PRIVATE KEY-----"
    public: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvXsnS6kT7zD5ebOS57gFv4+NHZx5\nq47xQgmZZUn5ZEd/Me8CPuVv+nCW2VY3cM1z3dcZ6c9LGokCRoIZ5s190g==\n-----END PUBLIC KEY-----"
  
database:
  read:
    driver: postgresql
    host: 192.168.0.251
    port: 5432
    database: sso
    schema: sso
    username: sso
    password: asd123qwe
  write:
    driver: postgresql
    host: 192.168.0.251
    port: 5432
    database: sso
    schema: sso
    username: sso
    password: asd123qwe