services:
  # db:
  #   image: postgres:17.2-alpine
  #   restart: always
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   # or set shared memory limit when deploy via swarm stack
  #   #volumes:
  #   #  - type: tmpfs
  #   #    target: /dev/shm
  #   #    tmpfs:
  #   #      size: 134217728 # 128*2^20 bytes = 128Mb
  #   volumes:
  #     - postgres_sso:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ryuze
  #     POSTGRES_PASSWORD: asd123qwe
  #     POSTGRES_DB: sso
  #   ports:
  #     - "5433:5432"
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - README.md
            - config-*
    ports:
      - 8050:8080

# volumes:
#   postgres_sso: 