// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationToken struct {
	ID         string
	SessionID  pgtype.Text
	InsertDate pgtype.Timestamp
}

type Session struct {
	ID                  string
	UserID              pgtype.Text
	ClientID            string
	CodeChallenge       string
	CodeChallengeMethod string
	Scopes              pgtype.Text
	InsertDate          pgtype.Timestamp
}

type User struct {
	ID         string
	Name       string
	Dot        pgtype.Timestamp
	Password   string
	InsertDate pgtype.Timestamp
}
