// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	Code       pgtype.Text
	Type       pgtype.Text
	InsertDate pgtype.Timestamp
}

type Client struct {
	ID            string
	Name          string
	Type          int32
	Secret        pgtype.Text
	TokenLivetime pgtype.Int8
}

type ClientRedirect struct {
	ClientID pgtype.Text
	Uri      string
}

type ClientType struct {
	ID   int32
	Name pgtype.Text
}

type Session struct {
	ID         pgtype.Text
	UserID     pgtype.Text
	InsertDate pgtype.Timestamp
}

type User struct {
	ID         string
	Name       string
	Dot        pgtype.Timestamp
	Password   string
	InsertDate pgtype.Timestamp
}
