// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_UNAUTHENTICATED-401]
	_ = x[ERR_INTERNAL_ERROR-500]
	_ = x[ERR_FORBIDDEN-403]
	_ = x[ERR_BAD_REQUEST-400]
	_ = x[ERR_CONFLICT-409]
}

const (
	_ErrorCode_name_0 = "ERR_BAD_REQUESTERR_UNAUTHENTICATED"
	_ErrorCode_name_1 = "ERR_FORBIDDEN"
	_ErrorCode_name_2 = "ERR_CONFLICT"
	_ErrorCode_name_3 = "ERR_INTERNAL_ERROR"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 15, 34}
)

func (i ErrorCode) String() string {
	switch {
	case 400 <= i && i <= 401:
		i -= 400
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case i == 403:
		return _ErrorCode_name_1
	case i == 409:
		return _ErrorCode_name_2
	case i == 500:
		return _ErrorCode_name_3
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
